### ISSUE TITLE
Recipes Missing

### ISSUE THREAD

**Issue by Degus22** [inzhefop/extrautilitiesreborn#3]
To my understanding are some recipes missing, when I search in JEI for what I can do with Ender Quarry Upgrade Base I only see the following two:
![grafik](https://user-images.githubusercontent.com/52410669/194828290-d0060570-7253-4b25-aa3d-e60d1b4a4592.png)
even though there are these in JEI:
![grafik](https://user-images.githubusercontent.com/52410669/194828641-45104a92-7244-43e3-a56f-8b540488e2b8.png)

**Comment by inzhefop** [comment]
Theres no jei integration for these items yet. You find the crafting process in the description. You have to use the Enchanter/Resonantor for some recipes

**Comment by Degus22** [comment]
ahh okay, thanks for the help

**Comment by DeleteMetaInf** [comment]
@inzhefop Do you have an ETA on when enchanter and resonator JEI integration will be added?

I am a bit hesitant to include Extra Utilities Reborn in my modpack—although I really want to—because there’s no JEI integration. I love EU Reborn, and I would be ecstatic if this is something you could add in the near future!
